//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnotherFlux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnotherFlux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;RecTypes&quot;: {
        ///    &quot;Custom Data&quot;: 15,
        ///    &quot;Location Events &amp; Dialogue&quot;: 12,
        ///    &quot;Location Exits&quot;: 9,
        ///    &quot;Location Map&quot;: 1,
        ///    &quot;Location Tile Assembly L12&quot;: 5,
        ///    &quot;Location Tile Assembly L3&quot;: 7,
        ///    &quot;Overworld Events&quot;: 2,
        ///    &quot;Overworld Exits&quot;: 3,
        ///    &quot;Overworld Map&quot;: 0,
        ///    &quot;Overworld Music Transition&quot;: 4,
        ///    &quot;Overworld Tile Assembly L12&quot;: 6,
        ///    &quot;Overworld Tile Assembly L3&quot;: 8,
        ///    &quot;Overworld Tile Properties&quot;: 10,
        ///    &quot;Strings&quot;: 11,
        ///    &quot;Substrings&quot;: 14,
        ///    &quot;Treasure&quot;: 13
        ///  },
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RomProperties {
            get {
                return ResourceManager.GetString("RomProperties", resourceCulture);
            }
        }
    }
}
